# Generated by Django 3.2.12 on 2022-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
